---

- block:
  - name: Install libselinux-python (yum)
    yum: state=present name=libselinux-python
    when: ansible_pkg_mgr == "yum"
  - name: Install python-selinux (apt)
    apt: state=present name=python-selinux
    when: ansible_pkg_mgr == "apt"
  become: yes

- name: Set zeppelin_bundle_name
  set_fact:
    zeppelin_bundle_name: "zeppelin-{{ zeppelin_version }}-bin-all"
- debug: var=zeppelin_bundle_name

- name: Load binary tarbll MD5
  set_fact:
    zeppelin_binary_md5: "{{ item.split(': ')|last|replace(' ', '')|lower }}"
  with_url: [ "{{ zeppelin_url_base }}/zeppelin-{{ zeppelin_version }}/{{ zeppelin_bundle_name }}.tgz.md5" ]
- debug: var=zeppelin_binary_md5

- name: Ensure {{ zeppelin_cache_dir }} exists
  file: path={{ zeppelin_cache_dir }} state=directory

- name: Download binary tarball
  get_url:
    url: "{{ zeppelin_url_base }}/zeppelin-{{ zeppelin_version }}/{{ zeppelin_bundle_name }}.tgz"
    dest: "{{ zeppelin_cache_dir }}/{{ zeppelin_bundle_name }}.tgz"
    checksum: md5:{{ zeppelin_binary_md5 }}

- name: Ensure {{ zeppelin_dir_base }} exists
  file: path={{ zeppelin_dir_base }} state=directory
  become: yes

- name: Unpack the distribution
  unarchive:
    src:   "{{ zeppelin_cache_dir }}/{{ zeppelin_bundle_name }}.tgz"
    dest:  "{{ zeppelin_dir_base }}"
    owner: root
    group: root
    copy:  no
    creates: "{{ zeppelin_dir_base }}/{{ zeppelin_bundle_name }}/LICENSE"
  become: yes

- name: Create canonical folder with symlink
  file: state=link path={{ zeppelin_dir_base }}/zeppelin src={{ zeppelin_bundle_name }}
  become: yes

- name: Set environment variables globally
  template: src=profile.sh.j2 dest=/etc/profile.d/zeppelin.sh
  become: true

- block:

  - name: Install monit (yum)
    yum: state=present name=monit
    when: ansible_pkg_mgr == "yum"
# - name: Install monit (apt)
#   apt: state=present name=monit
#   when: ansible_pkg_mgr == "apt"

  - name: start monit service
    service: state=started name=monit

  - name: Install zeppelin monitrc
    template: src=monitrc.j2 dest=/etc/monit.d/zeppelin

  - name: Reload monit
    monit: state=reloaded name=zeppelin

  become: yes

